// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qsfyjsuzxgtmujkwibvp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFzZnlqc3V6eGd0bXVqa3dpYnZwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY0NTkzMTEsImV4cCI6MjA3MjAzNTMxMX0._K4wrhHfIBvePLaIOBhdDJ1C6n8FWkMit7Z49pX4h-0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});